global:
  scrape_interval: 5s
  scrape_timeout: 4s

scrape_configs:
  - job_name: account-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8080"]

  - job_name: pix-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8081"]
